apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    app: {{ include "web.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.secrets.PORT }}
      targetPort: {{ .Values.secrets.PORT }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "web.name" . }}
    release: {{ .Release.Name }}
