// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	Access          string           `json:"access"`
	MaxWidth        pgtype.Int4      `json:"max_width"`
	MaxHeight       pgtype.Int4      `json:"max_height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type LimitUsage struct {
	ID                       pgtype.UUID `json:"id"`
	Used                     int32       `json:"used"`
	UserID                   pgtype.UUID `json:"user_id"`
	PackagePermissionLimitID pgtype.UUID `json:"package_permission_limit_id"`
}

type Order struct {
	ID             pgtype.UUID      `json:"id"`
	IdempotencyKey string           `json:"idempotency_key"`
	BoardID        pgtype.UUID      `json:"board_id"`
	SellerID       pgtype.UUID      `json:"seller_id"`
	BuyerUserID    pgtype.Text      `json:"buyer_user_id"`
	BuyerName      pgtype.Text      `json:"buyer_name"`
	Email          pgtype.Text      `json:"email"`
	Phone          pgtype.Text      `json:"phone"`
	Address        string           `json:"address"`
	City           pgtype.Text      `json:"city"`
	PostalCode     pgtype.Text      `json:"postal_code"`
	Country        pgtype.Text      `json:"country"`
	AmountTotal    pgtype.Numeric   `json:"amount_total"`
	PaymentMethod  string           `json:"payment_method"`
	CardLast4      pgtype.Text      `json:"card_last4"`
	Status         string           `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}

type OrderItem struct {
	ID       pgtype.UUID    `json:"id"`
	OrderID  pgtype.UUID    `json:"order_id"`
	WidgetID pgtype.UUID    `json:"widget_id"`
	Name     string         `json:"name"`
	Sku      string         `json:"sku"`
	Price    pgtype.Numeric `json:"price"`
	Quantity int32          `json:"quantity"`
}

type Package struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	Price           string      `json:"price"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
}

type PackagePermissionLimit struct {
	ID           pgtype.UUID `json:"id"`
	PackageID    pgtype.UUID `json:"package_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	LimitCount   pgtype.Int4 `json:"limit_count"`
}

type Permission struct {
	ID          pgtype.UUID `json:"id"`
	Action      string      `json:"action"`
	Subject     string      `json:"subject"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Role struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
}

type RolePermission struct {
	ID           pgtype.UUID `json:"id"`
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type SmartWidget struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	BoardID         pgtype.UUID      `json:"board_id"`
	Sku             string           `json:"sku"`
	Photo           pgtype.Text      `json:"photo"`
	Quantity        int32            `json:"quantity"`
	Price           pgtype.Numeric   `json:"price"`
	Name            string           `json:"name"`
	PosX            pgtype.Numeric   `json:"pos_x"`
	PosY            pgtype.Numeric   `json:"pos_y"`
	Width           int32            `json:"width"`
	Height          int32            `json:"height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type Subscription struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	PackageID     pgtype.UUID      `json:"package_id"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	PaymentMethod string           `json:"payment_method"`
	Amount        pgtype.Numeric   `json:"amount"`
}

type User struct {
	ID                     pgtype.UUID      `json:"id"`
	Name                   string           `json:"name"`
	Email                  string           `json:"email"`
	Password               pgtype.Text      `json:"password"`
	Provider               pgtype.Text      `json:"provider"`
	RefreshToken           pgtype.Text      `json:"refresh_token"`
	ResetPasswordToken     pgtype.Text      `json:"reset_password_token"`
	ResetPasswordExpiresAt pgtype.Timestamp `json:"reset_password_expires_at"`
	PrimaryUserID          pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID        pgtype.UUID      `json:"secondary_user_id"`
}

type UserRole struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}
