// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	ClearRefreshToken(ctx context.Context, id pgtype.UUID) error
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ============================================================================
	// 4. Access Control (RBAC) & Quotas
	// ============================================================================
	GetAccessContextByUserId(ctx context.Context, userID pgtype.UUID) ([]GetAccessContextByUserIdRow, error)
	// ============================================================================
	// 1. Defaults & Seed Checks
	// ============================================================================
	GetPackageBySlug(ctx context.Context, slug string) (Package, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	// ============================================================================
	// 2. User & Signup Queries
	// ============================================================================
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	GetUserByResetToken(ctx context.Context, resetPasswordToken pgtype.Text) (User, error)
	GetUserQuotas(ctx context.Context, userID pgtype.UUID) ([]GetUserQuotasRow, error)
	// ============================================================================
	// 3. Password & Session Management Updates
	// ============================================================================
	SetResetPasswordToken(ctx context.Context, arg SetResetPasswordTokenParams) error
	UpdatePasswordAndClearTokens(ctx context.Context, arg UpdatePasswordAndClearTokensParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
}

var _ Querier = (*Queries)(nil)
