// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const grantRolePermission = `-- name: GrantRolePermission :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
`

type GrantRolePermissionParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error {
	_, err := q.db.Exec(ctx, grantRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const insertPackage = `-- name: InsertPackage :one
INSERT INTO packages (title, slug, price, primary_user_id, secondary_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertPackageParams struct {
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	Price           string      `json:"price"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
}

func (q *Queries) InsertPackage(ctx context.Context, arg InsertPackageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertPackage,
		arg.Title,
		arg.Slug,
		arg.Price,
		arg.PrimaryUserID,
		arg.SecondaryUserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertPackagePermissionLimit = `-- name: InsertPackagePermissionLimit :exec
INSERT INTO package_permission_limits (package_id, permission_id, limit_count)
VALUES ($1, $2, $3)
`

type InsertPackagePermissionLimitParams struct {
	PackageID    pgtype.UUID `json:"package_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
	LimitCount   pgtype.Int4 `json:"limit_count"`
}

func (q *Queries) InsertPackagePermissionLimit(ctx context.Context, arg InsertPackagePermissionLimitParams) error {
	_, err := q.db.Exec(ctx, insertPackagePermissionLimit, arg.PackageID, arg.PermissionID, arg.LimitCount)
	return err
}

const insertPermission = `-- name: InsertPermission :one
INSERT INTO permissions (action, subject, name, endpoint, method, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action, subject
`

type InsertPermissionParams struct {
	Action      string      `json:"action"`
	Subject     string      `json:"subject"`
	Name        string      `json:"name"`
	Endpoint    string      `json:"endpoint"`
	Method      string      `json:"method"`
	Description pgtype.Text `json:"description"`
}

type InsertPermissionRow struct {
	ID      pgtype.UUID `json:"id"`
	Action  string      `json:"action"`
	Subject string      `json:"subject"`
}

func (q *Queries) InsertPermission(ctx context.Context, arg InsertPermissionParams) (InsertPermissionRow, error) {
	row := q.db.QueryRow(ctx, insertPermission,
		arg.Action,
		arg.Subject,
		arg.Name,
		arg.Endpoint,
		arg.Method,
		arg.Description,
	)
	var i InsertPermissionRow
	err := row.Scan(&i.ID, &i.Action, &i.Subject)
	return i, err
}

const insertRole = `-- name: InsertRole :one
INSERT INTO roles (title, slug, primary_user_id, secondary_user_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertRoleParams struct {
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
}

func (q *Queries) InsertRole(ctx context.Context, arg InsertRoleParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRole,
		arg.Title,
		arg.Slug,
		arg.PrimaryUserID,
		arg.SecondaryUserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSubscription = `-- name: InsertSubscription :exec
INSERT INTO subscriptions (user_id, package_id, start_date, end_date, payment_method, amount)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertSubscriptionParams struct {
	UserID        pgtype.UUID      `json:"user_id"`
	PackageID     pgtype.UUID      `json:"package_id"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	PaymentMethod string           `json:"payment_method"`
	Amount        pgtype.Numeric   `json:"amount"`
}

func (q *Queries) InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, insertSubscription,
		arg.UserID,
		arg.PackageID,
		arg.StartDate,
		arg.EndDate,
		arg.PaymentMethod,
		arg.Amount,
	)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (name, email, password, provider, primary_user_id, secondary_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertUserParams struct {
	Name            string      `json:"name"`
	Email           string      `json:"email"`
	Password        pgtype.Text `json:"password"`
	Provider        pgtype.Text `json:"provider"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Provider,
		arg.PrimaryUserID,
		arg.SecondaryUserID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const truncateAllTables = `-- name: TruncateAllTables :exec
TRUNCATE TABLE
    order_items,
    orders,
    smart_widgets,
    boards,
    limit_usages,
    subscriptions,
    package_permission_limits,
    packages,
    user_roles,
    role_permissions,
    roles,
    permissions,
    users
RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateAllTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateAllTables)
	return err
}
