FROM node:24-alpine

WORKDIR /app

RUN npm install -g pnpm@9.0.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY packages/common/package.json packages/common/package.json
COPY apps/web/package.json apps/web/package.json

RUN pnpm install

COPY packages/common packages/common
COPY apps/web apps/web

EXPOSE 3000

ENV NEXT_TELEMETRY_DISABLED=1

# Add runtime environment variables for Next.js
ENV NEXT_PUBLIC_GATEWAY_URL=http://localhost:3001
ENV NEXT_PUBLIC_SOCKET_URL=http://localhost:3001

# CMD ["npm", "run", "dev"]

CMD ["pnpm", "--filter", "@collab-grid/web", "dev"]
