@baseUrl = http://localhost:3001/api/v1/boards
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI2MmFhMTIxLTkzYzMtNDU5Ny04ZjBjLWQ1YTVkZGY0YWExYyIsImVtYWlsIjoibXJpZHVsQGV4YW1wbGUuY29tIiwiZXhwIjoxNzg3NjM5MTYzLCJpYXQiOjE3ODc2MzgyNjN9.t-oH4jDA8Pc_Whrlc9zWBi5S-D-z3TqFJlxyZxCCzzQ
@boardId = e5dc07de-b742-4f1b-8748-747bceff8013
@slug = my-board


### Get All Boards

GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Create Board

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "My Board",
  "access": "restricted"
}


### Create Board (Public)

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Public Board",
  "access": "public",
  "maxWidth": 8000,
  "maxHeight": 6000
}


### Find Board By Slug

GET {{baseUrl}}/by-slug/{{slug}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Update Board

PATCH {{baseUrl}}/{{boardId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Updated Board Name",
  "access": "public"
}


### Delete Board

DELETE {{baseUrl}}/{{boardId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
