ingress:
  enabled: true
  name: lootboard-ingress
  ingressClassName: nginx

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    
    # Passes X-Forwarded-For, X-Forwarded-Host, and X-Forwarded-Proto to upstream pods
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    # Preserves the host header sent by the browser
    nginx.ingress.kubernetes.io/upstream-vhost: "$host"
    # Prevents Nginx from rewriting downstream 302/301 redirects
    nginx.ingress.kubernetes.io/proxy-redirect-off: "true"

  tls:
    - secretName: lootboard-ssl-secret
      hosts:
        - lootboard.asif-haque.com
        - www.lootboard.asif-haque.com
        - lootboard-api.asif-haque.com
        - www.lootboard-api.asif-haque.com

  hosts:
    - host: lootboard.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-web
          servicePort: 3000
    - host: www.lootboard.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-web
          servicePort: 3000
    - host: lootboard-api.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-api
          servicePort: 3001
    - host: www.lootboard-api.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-api
          servicePort: 3001
