ingress:
  enabled: true
  name: lootboard-ingress
  ingressClassName: nginx

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Forwarded-Host $host";
      more_set_headers "X-Forwarded-Proto $scheme";
    nginx.ingress.kubernetes.io/proxy-redirect-from: "http://0.0.0.0:3000/"
    nginx.ingress.kubernetes.io/proxy-redirect-to: "https://lootboard.asif-haque.com/"

  tls:
    - secretName: lootboard-ssl-secret
      hosts:
        - lootboard.asif-haque.com
        - www.lootboard.asif-haque.com
        - lootboard-api.asif-haque.com
        - www.lootboard-api.asif-haque.com

  hosts:
    - host: lootboard.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-web
          servicePort: 3000
    - host: www.lootboard.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-web
          servicePort: 3000
    - host: lootboard-api.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-api
          servicePort: 3001
    - host: www.lootboard-api.asif-haque.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: lootboard-api
          servicePort: 3001
