apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    app: {{ include "api.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  ACCESS_TOKEN_SECRET: {{ .Values.secrets.ACCESS_TOKEN_SECRET | quote }}
  ACCESS_TOKEN_EXPIRATION: {{ .Values.secrets.ACCESS_TOKEN_EXPIRATION | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.secrets.REFRESH_TOKEN_SECRET | quote }}
  REFRESH_TOKEN_EXPIRATION: {{ .Values.secrets.REFRESH_TOKEN_EXPIRATION | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.GOOGLE_CLIENT_SECRET | quote }}
  GOOGLE_CALLBACK_URL: {{ .Values.secrets.GOOGLE_CALLBACK_URL | quote }}
  CLIENT_URL: {{ .Values.secrets.CLIENT_URL | quote }}
  CORS_ORIGIN: {{ .Values.secrets.CORS_ORIGIN | quote }}
  PORT: {{ .Values.secrets.PORT | quote }}
  SMTP_HOST: {{ .Values.secrets.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.secrets.SMTP_PORT | quote }}
  SMTP_SECURE: {{ .Values.secrets.SMTP_SECURE | quote }}
  SMTP_USER: {{ .Values.secrets.SMTP_USER | quote }}
  SMTP_PASS: {{ .Values.secrets.SMTP_PASS | quote }}
  MAIL_FROM: {{ .Values.secrets.MAIL_FROM | quote }}
  RESET_TOKEN_EXPIRATION: {{ .Values.secrets.RESET_TOKEN_EXPIRATION | quote }}
  RESET_PASSWORD_URL: {{ .Values.secrets.RESET_PASSWORD_URL | quote }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL | quote }}
  RABBITMQ_URL: {{ .Values.secrets.RABBITMQ_URL | quote }}
  WS_TOKEN_SECRET: {{ .Values.secrets.WS_TOKEN_SECRET | quote }}
