@baseUrl = http://localhost:3001/api/v1/auth
@accessToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIxNDFjMjM2LWYxNjctNDRlNi05YjllLTFmOGQ1NWEyMGRiOCIsImVtYWlsIjoibXJpZHVsQGV4YW1wbGUuY29tIiwiZXhwIjoxNzg3NzI0NjA2LCJpYXQiOjE3ODc3MjM3MDZ9.MmsvHCBPARpSXEUvANpS4buzAmD6mKLcp9ooSunD0UA 

### Current User
GET {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{accessToken}}



 #==================================================================================================== Those are not implemented yet ================================================================================ 

### Change Password

PUT {{baseUrl}}/change-password
Content-Type: application/json

{
  "email": "mridul@example.com",
  "password": "SecurePassword123!"
}