// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
`

type AssignUserRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleID)
	return err
}

const clearRefreshToken = `-- name: ClearRefreshToken :exec
UPDATE users
SET refresh_token = NULL
WHERE id = $1
`

func (q *Queries) ClearRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRefreshToken, id)
	return err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (
    user_id, package_id, start_date, end_date, payment_method, amount
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSubscriptionParams struct {
	UserID        pgtype.UUID      `json:"user_id"`
	PackageID     pgtype.UUID      `json:"package_id"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	PaymentMethod string           `json:"payment_method"`
	Amount        pgtype.Numeric   `json:"amount"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createSubscription,
		arg.UserID,
		arg.PackageID,
		arg.StartDate,
		arg.EndDate,
		arg.PaymentMethod,
		arg.Amount,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, provider)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, password, provider, refresh_token, reset_password_token, reset_password_expires_at, primary_user_id, secondary_user_id
`

type CreateUserParams struct {
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Password pgtype.Text `json:"password"`
	Provider pgtype.Text `json:"provider"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Provider,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.RefreshToken,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpiresAt,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getAccessContextByUserId = `-- name: GetAccessContextByUserId :many

SELECT
    r.slug AS role_slug,
    r.title AS role_title,
    p.action,
    p.subject
FROM user_roles ur
INNER JOIN roles r ON ur.role_id = r.id
INNER JOIN role_permissions rp ON r.id = rp.role_id
INNER JOIN permissions p ON rp.permission_id = p.id
WHERE ur.user_id = $1
`

type GetAccessContextByUserIdRow struct {
	RoleSlug  string `json:"role_slug"`
	RoleTitle string `json:"role_title"`
	Action    string `json:"action"`
	Subject   string `json:"subject"`
}

// ============================================================================
// 4. Access Control (RBAC) & Quotas
// ============================================================================
func (q *Queries) GetAccessContextByUserId(ctx context.Context, userID pgtype.UUID) ([]GetAccessContextByUserIdRow, error) {
	rows, err := q.db.Query(ctx, getAccessContextByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccessContextByUserIdRow
	for rows.Next() {
		var i GetAccessContextByUserIdRow
		if err := rows.Scan(
			&i.RoleSlug,
			&i.RoleTitle,
			&i.Action,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackageBySlug = `-- name: GetPackageBySlug :one

SELECT id, title, slug, price, primary_user_id, secondary_user_id
FROM packages
WHERE slug = $1
LIMIT 1
`

// ============================================================================
// 1. Defaults & Seed Checks
// ============================================================================
func (q *Queries) GetPackageBySlug(ctx context.Context, slug string) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageBySlug, slug)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, title, slug, primary_user_id, secondary_user_id
FROM roles
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetRoleBySlug(ctx context.Context, slug string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, name, email, password, provider, refresh_token, reset_password_token, reset_password_expires_at, primary_user_id, secondary_user_id
FROM users
WHERE email = $1
LIMIT 1
`

// ============================================================================
// 2. User & Signup Queries
// ============================================================================
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.RefreshToken,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpiresAt,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, name, email, password, provider, refresh_token, reset_password_token, reset_password_expires_at, primary_user_id, secondary_user_id
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.RefreshToken,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpiresAt,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT id, name, email, password, provider, refresh_token, reset_password_token, reset_password_expires_at, primary_user_id, secondary_user_id
FROM users
WHERE refresh_token = $1
LIMIT 1
`

func (q *Queries) GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, refreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.RefreshToken,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpiresAt,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, name, email, password, provider, refresh_token, reset_password_token, reset_password_expires_at, primary_user_id, secondary_user_id
FROM users
WHERE reset_password_token = $1
LIMIT 1
`

func (q *Queries) GetUserByResetToken(ctx context.Context, resetPasswordToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByResetToken, resetPasswordToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Provider,
		&i.RefreshToken,
		&i.ResetPasswordToken,
		&i.ResetPasswordExpiresAt,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const getUserQuotas = `-- name: GetUserQuotas :many
SELECT
    p.action,
    p.subject,
    ppl.limit_count,
    COALESCE(SUM(lu.used), 0)::bigint AS total_used
FROM subscriptions s
INNER JOIN package_permission_limits ppl ON s.package_id = ppl.package_id
INNER JOIN permissions p ON ppl.permission_id = p.id
LEFT JOIN limit_usages lu ON ppl.id = lu.package_permission_limit_id AND lu.user_id = $1
WHERE s.user_id = $1
  AND (s.end_date IS NULL OR s.end_date > NOW())
GROUP BY p.action, p.subject, ppl.limit_count
`

type GetUserQuotasRow struct {
	Action     string      `json:"action"`
	Subject    string      `json:"subject"`
	LimitCount pgtype.Int4 `json:"limit_count"`
	TotalUsed  int64       `json:"total_used"`
}

func (q *Queries) GetUserQuotas(ctx context.Context, userID pgtype.UUID) ([]GetUserQuotasRow, error) {
	rows, err := q.db.Query(ctx, getUserQuotas, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserQuotasRow
	for rows.Next() {
		var i GetUserQuotasRow
		if err := rows.Scan(
			&i.Action,
			&i.Subject,
			&i.LimitCount,
			&i.TotalUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setResetPasswordToken = `-- name: SetResetPasswordToken :exec

UPDATE users
SET reset_password_token = $1,
    reset_password_expires_at = $2
WHERE id = $3
`

type SetResetPasswordTokenParams struct {
	ResetPasswordToken     pgtype.Text      `json:"reset_password_token"`
	ResetPasswordExpiresAt pgtype.Timestamp `json:"reset_password_expires_at"`
	ID                     pgtype.UUID      `json:"id"`
}

// ============================================================================
// 3. Password & Session Management Updates
// ============================================================================
func (q *Queries) SetResetPasswordToken(ctx context.Context, arg SetResetPasswordTokenParams) error {
	_, err := q.db.Exec(ctx, setResetPasswordToken, arg.ResetPasswordToken, arg.ResetPasswordExpiresAt, arg.ID)
	return err
}

const updatePasswordAndClearTokens = `-- name: UpdatePasswordAndClearTokens :exec
UPDATE users
SET password = $1,
    reset_password_token = NULL,
    reset_password_expires_at = NULL,
    refresh_token = NULL
WHERE id = $2
`

type UpdatePasswordAndClearTokensParams struct {
	Password pgtype.Text `json:"password"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdatePasswordAndClearTokens(ctx context.Context, arg UpdatePasswordAndClearTokensParams) error {
	_, err := q.db.Exec(ctx, updatePasswordAndClearTokens, arg.Password, arg.ID)
	return err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE users
SET refresh_token = $1
WHERE id = $2
`

type UpdateRefreshTokenParams struct {
	RefreshToken pgtype.Text `json:"refresh_token"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.RefreshToken, arg.ID)
	return err
}
