// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (
    primary_user_id,
    secondary_user_id,
    name,
    slug,
    access,
    max_width,
    max_height
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, primary_user_id, secondary_user_id, name, slug, access, max_width, max_height, created_at, updated_at
`

type CreateBoardParams struct {
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
	Name            string      `json:"name"`
	Slug            string      `json:"slug"`
	Access          string      `json:"access"`
	MaxWidth        pgtype.Int4 `json:"max_width"`
	MaxHeight       pgtype.Int4 `json:"max_height"`
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.PrimaryUserID,
		arg.SecondaryUserID,
		arg.Name,
		arg.Slug,
		arg.Access,
		arg.MaxWidth,
		arg.MaxHeight,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.Name,
		&i.Slug,
		&i.Access,
		&i.MaxWidth,
		&i.MaxHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :exec
DELETE FROM boards
WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoard, id)
	return err
}

const getBoardById = `-- name: GetBoardById :one
SELECT b.id, b.primary_user_id, b.secondary_user_id, b.name, b.slug, b.access, b.max_width, b.max_height, b.created_at, b.updated_at, COUNT(sw.id)::bigint AS widget_count
FROM boards b
LEFT JOIN smart_widgets sw ON sw.board_id = b.id
WHERE b.id = $1 AND b.primary_user_id = $2
GROUP BY b.id
`

type GetBoardByIdParams struct {
	ID            pgtype.UUID `json:"id"`
	PrimaryUserID pgtype.UUID `json:"primary_user_id"`
}

type GetBoardByIdRow struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	Access          string           `json:"access"`
	MaxWidth        pgtype.Int4      `json:"max_width"`
	MaxHeight       pgtype.Int4      `json:"max_height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	WidgetCount     int64            `json:"widget_count"`
}

func (q *Queries) GetBoardById(ctx context.Context, arg GetBoardByIdParams) (GetBoardByIdRow, error) {
	row := q.db.QueryRow(ctx, getBoardById, arg.ID, arg.PrimaryUserID)
	var i GetBoardByIdRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.Name,
		&i.Slug,
		&i.Access,
		&i.MaxWidth,
		&i.MaxHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WidgetCount,
	)
	return i, err
}

const getBoardBySlug = `-- name: GetBoardBySlug :one
SELECT b.id, b.primary_user_id, b.secondary_user_id, b.name, b.slug, b.access, b.max_width, b.max_height, b.created_at, b.updated_at, COUNT(sw.id)::bigint AS widget_count
FROM boards b
LEFT JOIN smart_widgets sw ON sw.board_id = b.id
WHERE b.slug = $1 AND b.primary_user_id = $2
GROUP BY b.id
`

type GetBoardBySlugParams struct {
	Slug          string      `json:"slug"`
	PrimaryUserID pgtype.UUID `json:"primary_user_id"`
}

type GetBoardBySlugRow struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	Access          string           `json:"access"`
	MaxWidth        pgtype.Int4      `json:"max_width"`
	MaxHeight       pgtype.Int4      `json:"max_height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	WidgetCount     int64            `json:"widget_count"`
}

func (q *Queries) GetBoardBySlug(ctx context.Context, arg GetBoardBySlugParams) (GetBoardBySlugRow, error) {
	row := q.db.QueryRow(ctx, getBoardBySlug, arg.Slug, arg.PrimaryUserID)
	var i GetBoardBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.Name,
		&i.Slug,
		&i.Access,
		&i.MaxWidth,
		&i.MaxHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WidgetCount,
	)
	return i, err
}

const getBoardIdBySlug = `-- name: GetBoardIdBySlug :one
SELECT id
FROM boards
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetBoardIdBySlug(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBoardIdBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPublicBoardBySlug = `-- name: GetPublicBoardBySlug :one
SELECT b.id, b.primary_user_id, b.secondary_user_id, b.name, b.slug, b.access, b.max_width, b.max_height, b.created_at, b.updated_at, COUNT(sw.id)::bigint AS widget_count
FROM boards b
LEFT JOIN smart_widgets sw ON sw.board_id = b.id
WHERE b.slug = $1 AND b.access = 'public'
GROUP BY b.id
`

type GetPublicBoardBySlugRow struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	Access          string           `json:"access"`
	MaxWidth        pgtype.Int4      `json:"max_width"`
	MaxHeight       pgtype.Int4      `json:"max_height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	WidgetCount     int64            `json:"widget_count"`
}

func (q *Queries) GetPublicBoardBySlug(ctx context.Context, slug string) (GetPublicBoardBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublicBoardBySlug, slug)
	var i GetPublicBoardBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.Name,
		&i.Slug,
		&i.Access,
		&i.MaxWidth,
		&i.MaxHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WidgetCount,
	)
	return i, err
}

const listBoardsByPrimaryUserId = `-- name: ListBoardsByPrimaryUserId :many

SELECT b.id, b.primary_user_id, b.secondary_user_id, b.name, b.slug, b.access, b.max_width, b.max_height, b.created_at, b.updated_at, COUNT(sw.id)::bigint AS widget_count
FROM boards b
LEFT JOIN smart_widgets sw ON sw.board_id = b.id
WHERE b.primary_user_id = $1
GROUP BY b.id
ORDER BY b.created_at DESC
`

type ListBoardsByPrimaryUserIdRow struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	Name            string           `json:"name"`
	Slug            string           `json:"slug"`
	Access          string           `json:"access"`
	MaxWidth        pgtype.Int4      `json:"max_width"`
	MaxHeight       pgtype.Int4      `json:"max_height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	WidgetCount     int64            `json:"widget_count"`
}

// ============================================================================
// 1. Board Queries
// ============================================================================
func (q *Queries) ListBoardsByPrimaryUserId(ctx context.Context, primaryUserID pgtype.UUID) ([]ListBoardsByPrimaryUserIdRow, error) {
	rows, err := q.db.Query(ctx, listBoardsByPrimaryUserId, primaryUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBoardsByPrimaryUserIdRow
	for rows.Next() {
		var i ListBoardsByPrimaryUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryUserID,
			&i.SecondaryUserID,
			&i.Name,
			&i.Slug,
			&i.Access,
			&i.MaxWidth,
			&i.MaxHeight,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WidgetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards
SET name = COALESCE($1, name),
    access = COALESCE($2, access),
    max_width = COALESCE($3, max_width),
    max_height = COALESCE($4, max_height),
    updated_at = NOW()
WHERE id = $5
RETURNING id, primary_user_id, secondary_user_id, name, slug, access, max_width, max_height, created_at, updated_at
`

type UpdateBoardParams struct {
	Name      pgtype.Text `json:"name"`
	Access    pgtype.Text `json:"access"`
	MaxWidth  pgtype.Int4 `json:"max_width"`
	MaxHeight pgtype.Int4 `json:"max_height"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.Name,
		arg.Access,
		arg.MaxWidth,
		arg.MaxHeight,
		arg.ID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.Name,
		&i.Slug,
		&i.Access,
		&i.MaxWidth,
		&i.MaxHeight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
