// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForCreateSmartWidgets implements pgx.CopyFromSource.
type iteratorForCreateSmartWidgets struct {
	rows                 []CreateSmartWidgetsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSmartWidgets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSmartWidgets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PrimaryUserID,
		r.rows[0].SecondaryUserID,
		r.rows[0].BoardID,
		r.rows[0].Sku,
		r.rows[0].Photo,
		r.rows[0].Quantity,
		r.rows[0].Price,
		r.rows[0].Name,
		r.rows[0].Width,
		r.rows[0].Height,
	}, nil
}

func (r iteratorForCreateSmartWidgets) Err() error {
	return nil
}

func (q *Queries) CreateSmartWidgets(ctx context.Context, arg []CreateSmartWidgetsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"smart_widgets"}, []string{"primary_user_id", "secondary_user_id", "board_id", "sku", "photo", "quantity", "price", "name", "width", "height"}, &iteratorForCreateSmartWidgets{rows: arg})
}
