// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSmartWidget = `-- name: CreateSmartWidget :one
INSERT INTO smart_widgets (
    primary_user_id,
    secondary_user_id,
    board_id,
    sku,
    photo,
    quantity,
    price,
    name,
    width,
    height
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, primary_user_id, secondary_user_id, board_id, sku, photo, quantity, price, name, pos_x, pos_y, width, height, created_at, updated_at
`

type CreateSmartWidgetParams struct {
	PrimaryUserID   pgtype.UUID    `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID    `json:"secondary_user_id"`
	BoardID         pgtype.UUID    `json:"board_id"`
	Sku             string         `json:"sku"`
	Photo           pgtype.Text    `json:"photo"`
	Quantity        int32          `json:"quantity"`
	Price           pgtype.Numeric `json:"price"`
	Name            string         `json:"name"`
	Width           int32          `json:"width"`
	Height          int32          `json:"height"`
}

func (q *Queries) CreateSmartWidget(ctx context.Context, arg CreateSmartWidgetParams) (SmartWidget, error) {
	row := q.db.QueryRow(ctx, createSmartWidget,
		arg.PrimaryUserID,
		arg.SecondaryUserID,
		arg.BoardID,
		arg.Sku,
		arg.Photo,
		arg.Quantity,
		arg.Price,
		arg.Name,
		arg.Width,
		arg.Height,
	)
	var i SmartWidget
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.BoardID,
		&i.Sku,
		&i.Photo,
		&i.Quantity,
		&i.Price,
		&i.Name,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateSmartWidgetsParams struct {
	PrimaryUserID   pgtype.UUID    `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID    `json:"secondary_user_id"`
	BoardID         pgtype.UUID    `json:"board_id"`
	Sku             string         `json:"sku"`
	Photo           pgtype.Text    `json:"photo"`
	Quantity        int32          `json:"quantity"`
	Price           pgtype.Numeric `json:"price"`
	Name            string         `json:"name"`
	Width           int32          `json:"width"`
	Height          int32          `json:"height"`
}

const deleteSmartWidget = `-- name: DeleteSmartWidget :exec
DELETE FROM smart_widgets
WHERE id = $1
`

func (q *Queries) DeleteSmartWidget(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSmartWidget, id)
	return err
}

const getBoardExistsForUser = `-- name: GetBoardExistsForUser :one
SELECT EXISTS (
    SELECT 1
    FROM boards
    WHERE id = $1 AND primary_user_id = $2
)
`

type GetBoardExistsForUserParams struct {
	ID            pgtype.UUID `json:"id"`
	PrimaryUserID pgtype.UUID `json:"primary_user_id"`
}

func (q *Queries) GetBoardExistsForUser(ctx context.Context, arg GetBoardExistsForUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, getBoardExistsForUser, arg.ID, arg.PrimaryUserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getSmartWidgetById = `-- name: GetSmartWidgetById :one
SELECT sw.id, sw.primary_user_id, sw.secondary_user_id, sw.board_id, sw.sku, sw.photo, sw.quantity, sw.price, sw.name, sw.pos_x, sw.pos_y, sw.width, sw.height, sw.created_at, sw.updated_at, b.name AS board_name
FROM smart_widgets sw
LEFT JOIN boards b ON b.id = sw.board_id
WHERE sw.id = $1 AND sw.primary_user_id = $2
`

type GetSmartWidgetByIdParams struct {
	ID            pgtype.UUID `json:"id"`
	PrimaryUserID pgtype.UUID `json:"primary_user_id"`
}

type GetSmartWidgetByIdRow struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	BoardID         pgtype.UUID      `json:"board_id"`
	Sku             string           `json:"sku"`
	Photo           pgtype.Text      `json:"photo"`
	Quantity        int32            `json:"quantity"`
	Price           pgtype.Numeric   `json:"price"`
	Name            string           `json:"name"`
	PosX            pgtype.Numeric   `json:"pos_x"`
	PosY            pgtype.Numeric   `json:"pos_y"`
	Width           int32            `json:"width"`
	Height          int32            `json:"height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	BoardName       pgtype.Text      `json:"board_name"`
}

func (q *Queries) GetSmartWidgetById(ctx context.Context, arg GetSmartWidgetByIdParams) (GetSmartWidgetByIdRow, error) {
	row := q.db.QueryRow(ctx, getSmartWidgetById, arg.ID, arg.PrimaryUserID)
	var i GetSmartWidgetByIdRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.BoardID,
		&i.Sku,
		&i.Photo,
		&i.Quantity,
		&i.Price,
		&i.Name,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardName,
	)
	return i, err
}

const listSmartWidgetsByPrimaryUserId = `-- name: ListSmartWidgetsByPrimaryUserId :many

SELECT sw.id, sw.primary_user_id, sw.secondary_user_id, sw.board_id, sw.sku, sw.photo, sw.quantity, sw.price, sw.name, sw.pos_x, sw.pos_y, sw.width, sw.height, sw.created_at, sw.updated_at, b.name AS board_name
FROM smart_widgets sw
LEFT JOIN boards b ON b.id = sw.board_id
WHERE sw.primary_user_id = $1
  AND (
    $2::uuid IS NULL
    OR sw.board_id = $2
  )
ORDER BY sw.created_at DESC
`

type ListSmartWidgetsByPrimaryUserIdParams struct {
	PrimaryUserID pgtype.UUID `json:"primary_user_id"`
	BoardID       pgtype.UUID `json:"board_id"`
}

type ListSmartWidgetsByPrimaryUserIdRow struct {
	ID              pgtype.UUID      `json:"id"`
	PrimaryUserID   pgtype.UUID      `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID      `json:"secondary_user_id"`
	BoardID         pgtype.UUID      `json:"board_id"`
	Sku             string           `json:"sku"`
	Photo           pgtype.Text      `json:"photo"`
	Quantity        int32            `json:"quantity"`
	Price           pgtype.Numeric   `json:"price"`
	Name            string           `json:"name"`
	PosX            pgtype.Numeric   `json:"pos_x"`
	PosY            pgtype.Numeric   `json:"pos_y"`
	Width           int32            `json:"width"`
	Height          int32            `json:"height"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	BoardName       pgtype.Text      `json:"board_name"`
}

// ============================================================================
// 6. Inventory (Smart Widget) Queries
// ============================================================================
func (q *Queries) ListSmartWidgetsByPrimaryUserId(ctx context.Context, arg ListSmartWidgetsByPrimaryUserIdParams) ([]ListSmartWidgetsByPrimaryUserIdRow, error) {
	rows, err := q.db.Query(ctx, listSmartWidgetsByPrimaryUserId, arg.PrimaryUserID, arg.BoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSmartWidgetsByPrimaryUserIdRow
	for rows.Next() {
		var i ListSmartWidgetsByPrimaryUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryUserID,
			&i.SecondaryUserID,
			&i.BoardID,
			&i.Sku,
			&i.Photo,
			&i.Quantity,
			&i.Price,
			&i.Name,
			&i.PosX,
			&i.PosY,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSmartWidget = `-- name: UpdateSmartWidget :exec
UPDATE smart_widgets
SET name = COALESCE($1, name),
    sku = COALESCE($2, sku),
    quantity = COALESCE($3, quantity),
    price = COALESCE($4, price),
    photo = COALESCE($5, photo),
    board_id = COALESCE($6, board_id),
    width = COALESCE($7, width),
    height = COALESCE($8, height),
    updated_at = NOW()
WHERE id = $9
`

type UpdateSmartWidgetParams struct {
	Name     pgtype.Text    `json:"name"`
	Sku      pgtype.Text    `json:"sku"`
	Quantity pgtype.Int4    `json:"quantity"`
	Price    pgtype.Numeric `json:"price"`
	Photo    pgtype.Text    `json:"photo"`
	BoardID  pgtype.UUID    `json:"board_id"`
	Width    pgtype.Int4    `json:"width"`
	Height   pgtype.Int4    `json:"height"`
	ID       pgtype.UUID    `json:"id"`
}

func (q *Queries) UpdateSmartWidget(ctx context.Context, arg UpdateSmartWidgetParams) error {
	_, err := q.db.Exec(ctx, updateSmartWidget,
		arg.Name,
		arg.Sku,
		arg.Quantity,
		arg.Price,
		arg.Photo,
		arg.BoardID,
		arg.Width,
		arg.Height,
		arg.ID,
	)
	return err
}
