// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    idempotency_key,
    board_id,
    buyer_user_id,
    buyer_name,
    email,
    phone,
    address,
    city,
    postal_code,
    country,
    amount_total,
    payment_method,
    card_last4,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, idempotency_key, board_id, seller_id, buyer_user_id, buyer_name, email, phone, address, city, postal_code, country, amount_total, payment_method, card_last4, status, created_at
`

type CreateOrderParams struct {
	IdempotencyKey string         `json:"idempotency_key"`
	BoardID        pgtype.UUID    `json:"board_id"`
	BuyerUserID    pgtype.Text    `json:"buyer_user_id"`
	BuyerName      pgtype.Text    `json:"buyer_name"`
	Email          pgtype.Text    `json:"email"`
	Phone          pgtype.Text    `json:"phone"`
	Address        string         `json:"address"`
	City           pgtype.Text    `json:"city"`
	PostalCode     pgtype.Text    `json:"postal_code"`
	Country        pgtype.Text    `json:"country"`
	AmountTotal    pgtype.Numeric `json:"amount_total"`
	PaymentMethod  string         `json:"payment_method"`
	CardLast4      pgtype.Text    `json:"card_last4"`
	Status         string         `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.IdempotencyKey,
		arg.BoardID,
		arg.BuyerUserID,
		arg.BuyerName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.AmountTotal,
		arg.PaymentMethod,
		arg.CardLast4,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.BoardID,
		&i.SellerID,
		&i.BuyerUserID,
		&i.BuyerName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.AmountTotal,
		&i.PaymentMethod,
		&i.CardLast4,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

type CreateOrderItemsParams struct {
	OrderID  pgtype.UUID    `json:"order_id"`
	WidgetID pgtype.UUID    `json:"widget_id"`
	Name     string         `json:"name"`
	Sku      string         `json:"sku"`
	Price    pgtype.Numeric `json:"price"`
	Quantity int32          `json:"quantity"`
}

const getBoardIdById = `-- name: GetBoardIdById :one
SELECT id
FROM boards
WHERE id = $1
`

func (q *Queries) GetBoardIdById(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBoardIdById, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getOrderById = `-- name: GetOrderById :one
SELECT id, idempotency_key, board_id, seller_id, buyer_user_id, buyer_name, email, phone, address, city, postal_code, country, amount_total, payment_method, card_last4, status, created_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderById(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderById, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.BoardID,
		&i.SellerID,
		&i.BuyerUserID,
		&i.BuyerName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.PostalCode,
		&i.Country,
		&i.AmountTotal,
		&i.PaymentMethod,
		&i.CardLast4,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderIdByIdempotencyKey = `-- name: GetOrderIdByIdempotencyKey :one

SELECT id
FROM orders
WHERE idempotency_key = $1
`

// ============================================================================
// 9. Order Queries
// ============================================================================
func (q *Queries) GetOrderIdByIdempotencyKey(ctx context.Context, idempotencyKey string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOrderIdByIdempotencyKey, idempotencyKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listOrderItemsByOrderId = `-- name: ListOrderItemsByOrderId :many
SELECT id, widget_id, name, sku, price, quantity
FROM order_items
WHERE order_id = $1
`

type ListOrderItemsByOrderIdRow struct {
	ID       pgtype.UUID    `json:"id"`
	WidgetID pgtype.UUID    `json:"widget_id"`
	Name     string         `json:"name"`
	Sku      string         `json:"sku"`
	Price    pgtype.Numeric `json:"price"`
	Quantity int32          `json:"quantity"`
}

func (q *Queries) ListOrderItemsByOrderId(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsByOrderIdRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderId, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderItemsByOrderIdRow
	for rows.Next() {
		var i ListOrderItemsByOrderIdRow
		if err := rows.Scan(
			&i.ID,
			&i.WidgetID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByPrimaryUserID = `-- name: ListOrdersByPrimaryUserID :many
SELECT o.id, o.buyer_name, o.email, o.amount_total, o.payment_method,
       o.card_last4, o.status, o.created_at, o.board_id,
       b.name AS board_name,
       oi.id AS item_id, oi.name AS item_name, oi.sku AS item_sku,
       oi.price AS item_price, oi.quantity AS item_quantity
FROM orders o
JOIN boards b ON b.id = o.board_id
JOIN order_items oi ON oi.order_id = o.id
WHERE b.primary_user_id = $1
ORDER BY o.created_at DESC
`

type ListOrdersByPrimaryUserIDRow struct {
	ID            pgtype.UUID      `json:"id"`
	BuyerName     pgtype.Text      `json:"buyer_name"`
	Email         pgtype.Text      `json:"email"`
	AmountTotal   pgtype.Numeric   `json:"amount_total"`
	PaymentMethod string           `json:"payment_method"`
	CardLast4     pgtype.Text      `json:"card_last4"`
	Status        string           `json:"status"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	BoardID       pgtype.UUID      `json:"board_id"`
	BoardName     string           `json:"board_name"`
	ItemID        pgtype.UUID      `json:"item_id"`
	ItemName      string           `json:"item_name"`
	ItemSku       string           `json:"item_sku"`
	ItemPrice     pgtype.Numeric   `json:"item_price"`
	ItemQuantity  int32            `json:"item_quantity"`
}

func (q *Queries) ListOrdersByPrimaryUserID(ctx context.Context, primaryUserID pgtype.UUID) ([]ListOrdersByPrimaryUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByPrimaryUserID, primaryUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByPrimaryUserIDRow
	for rows.Next() {
		var i ListOrdersByPrimaryUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.BuyerName,
			&i.Email,
			&i.AmountTotal,
			&i.PaymentMethod,
			&i.CardLast4,
			&i.Status,
			&i.CreatedAt,
			&i.BoardID,
			&i.BoardName,
			&i.ItemID,
			&i.ItemName,
			&i.ItemSku,
			&i.ItemPrice,
			&i.ItemQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWidgetsForOrder = `-- name: ListWidgetsForOrder :many
SELECT id, name, sku, price, quantity
FROM smart_widgets
WHERE board_id = $1
  AND id = ANY($2::uuid[])
`

type ListWidgetsForOrderParams struct {
	BoardID   pgtype.UUID   `json:"board_id"`
	WidgetIds []pgtype.UUID `json:"widget_ids"`
}

type ListWidgetsForOrderRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Sku      string         `json:"sku"`
	Price    pgtype.Numeric `json:"price"`
	Quantity int32          `json:"quantity"`
}

func (q *Queries) ListWidgetsForOrder(ctx context.Context, arg ListWidgetsForOrderParams) ([]ListWidgetsForOrderRow, error) {
	rows, err := q.db.Query(ctx, listWidgetsForOrder, arg.BoardID, arg.WidgetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWidgetsForOrderRow
	for rows.Next() {
		var i ListWidgetsForOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Price,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
