// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: package.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePackage = `-- name: DeletePackage :exec
DELETE FROM packages
WHERE id = $1
`

// Delete a package.
func (q *Queries) DeletePackage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePackage, id)
	return err
}

const deletePackagePermissionLimits = `-- name: DeletePackagePermissionLimits :exec
DELETE FROM package_permission_limits
WHERE package_id = $1
`

// Delete all permission limits belonging to a package.
func (q *Queries) DeletePackagePermissionLimits(ctx context.Context, packageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePackagePermissionLimits, packageID)
	return err
}

const getPackageByID = `-- name: GetPackageByID :one
SELECT p.id,
       p.title,
       p.slug,
       p.price,
       p.primary_user_id,
       p.secondary_user_id,
       COUNT(s.id)::bigint AS subscriber_count
FROM packages p
LEFT JOIN subscriptions s ON s.package_id = p.id
WHERE p.id = $1
GROUP BY p.id
`

type GetPackageByIDRow struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	Price           string      `json:"price"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
	SubscriberCount int64       `json:"subscriber_count"`
}

// Single package with its active subscription count.
func (q *Queries) GetPackageByID(ctx context.Context, id pgtype.UUID) (GetPackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i GetPackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.SubscriberCount,
	)
	return i, err
}

const listPackagePermissionLimits = `-- name: ListPackagePermissionLimits :many
SELECT ppl.package_id,
       p.id AS permission_id,
       p.name AS permission_name,
       p.action AS permission_action,
       p.subject AS permission_subject,
       ppl.limit_count
FROM package_permission_limits ppl
JOIN permissions p ON p.id = ppl.permission_id
WHERE ppl.package_id = ANY($1::uuid[])
`

type ListPackagePermissionLimitsRow struct {
	PackageID         pgtype.UUID `json:"package_id"`
	PermissionID      pgtype.UUID `json:"permission_id"`
	PermissionName    string      `json:"permission_name"`
	PermissionAction  string      `json:"permission_action"`
	PermissionSubject string      `json:"permission_subject"`
	LimitCount        pgtype.Int4 `json:"limit_count"`
}

// Permission limits (with joined permission metadata) for the given packages.
func (q *Queries) ListPackagePermissionLimits(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListPackagePermissionLimitsRow, error) {
	rows, err := q.db.Query(ctx, listPackagePermissionLimits, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagePermissionLimitsRow
	for rows.Next() {
		var i ListPackagePermissionLimitsRow
		if err := rows.Scan(
			&i.PackageID,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionAction,
			&i.PermissionSubject,
			&i.LimitCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackages = `-- name: ListPackages :many
SELECT p.id,
       p.title,
       p.slug,
       p.price,
       p.primary_user_id,
       p.secondary_user_id,
       COUNT(s.id)::bigint AS subscriber_count
FROM packages p
LEFT JOIN subscriptions s ON s.package_id = p.id
GROUP BY p.id
ORDER BY p.title
`

type ListPackagesRow struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	Price           string      `json:"price"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
	SubscriberCount int64       `json:"subscriber_count"`
}

// All packages with their active subscription count.
func (q *Queries) ListPackages(ctx context.Context) ([]ListPackagesRow, error) {
	rows, err := q.db.Query(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagesRow
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Price,
			&i.PrimaryUserID,
			&i.SecondaryUserID,
			&i.SubscriberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantRolePermissions = `-- name: ListTenantRolePermissions :many

SELECT DISTINCT p.id, p.name, p.action, p.subject, p.description
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN roles r ON r.id = rp.role_id
WHERE r.slug = $1
ORDER BY p.subject, p.action
`

type ListTenantRolePermissionsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Action      string      `json:"action"`
	Subject     string      `json:"subject"`
	Description pgtype.Text `json:"description"`
}

// ============================================================================
// Package Queries
// ============================================================================
// Permissions exposed for building/assigning package quotas. Mirrors the TS
// service which joins permissions through the tenant role (TENANT_ROLE_SLUG).
func (q *Queries) ListTenantRolePermissions(ctx context.Context, slug string) ([]ListTenantRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listTenantRolePermissions, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantRolePermissionsRow
	for rows.Next() {
		var i ListTenantRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.Subject,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackage = `-- name: UpdatePackage :one
UPDATE packages
SET title = COALESCE($1, title),
    slug  = COALESCE($2, slug),
    price = COALESCE($3, price)
WHERE id = $4
RETURNING id, title, slug, price, primary_user_id, secondary_user_id
`

type UpdatePackageParams struct {
	Title pgtype.Text `json:"title"`
	Slug  pgtype.Text `json:"slug"`
	Price pgtype.Text `json:"price"`
	ID    pgtype.UUID `json:"id"`
}

// Partial update of a package. NULL arguments leave the column unchanged.
func (q *Queries) UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error) {
	row := q.db.QueryRow(ctx, updatePackage,
		arg.Title,
		arg.Slug,
		arg.Price,
		arg.ID,
	)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Price,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}
