// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	ClearRefreshToken(ctx context.Context, id pgtype.UUID) error
	CountUserSubscriptions(ctx context.Context, userID pgtype.UUID) (int32, error)
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItems(ctx context.Context, arg []CreateOrderItemsParams) (int64, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRolePermissions(ctx context.Context, arg CreateRolePermissionsParams) error
	CreateSmartWidget(ctx context.Context, arg CreateSmartWidgetParams) (SmartWidget, error)
	CreateSmartWidgets(ctx context.Context, arg []CreateSmartWidgetsParams) (int64, error)
	CreateSubUser(ctx context.Context, arg CreateSubUserParams) (CreateSubUserRow, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementLimitUsage(ctx context.Context, arg DecrementLimitUsageParams) (pgtype.UUID, error)
	DeleteBoard(ctx context.Context, id pgtype.UUID) error
	// Delete a package.
	DeletePackage(ctx context.Context, id pgtype.UUID) error
	// Delete all permission limits belonging to a package.
	DeletePackagePermissionLimits(ctx context.Context, packageID pgtype.UUID) error
	DeleteRole(ctx context.Context, id pgtype.UUID) error
	DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error
	DeleteSmartWidget(ctx context.Context, id pgtype.UUID) error
	DeleteSubUser(ctx context.Context, id pgtype.UUID) error
	DeleteUserRoles(ctx context.Context, userID pgtype.UUID) error
	// ============================================================================
	// 4. Access Control (RBAC) & Quotas
	// ============================================================================
	GetAccessContextByUserId(ctx context.Context, userID pgtype.UUID) ([]GetAccessContextByUserIdRow, error)
	GetActiveSubscriptions(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetBoardById(ctx context.Context, arg GetBoardByIdParams) (GetBoardByIdRow, error)
	GetBoardBySlug(ctx context.Context, arg GetBoardBySlugParams) (GetBoardBySlugRow, error)
	GetBoardExistsForUser(ctx context.Context, arg GetBoardExistsForUserParams) (bool, error)
	GetBoardIdById(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetBoardIdBySlug(ctx context.Context, slug string) (pgtype.UUID, error)
	GetLimitUsage(ctx context.Context, arg GetLimitUsageParams) (int32, error)
	GetOrderById(ctx context.Context, id pgtype.UUID) (Order, error)
	// ============================================================================
	// 9. Order Queries
	// ============================================================================
	GetOrderIdByIdempotencyKey(ctx context.Context, idempotencyKey string) (pgtype.UUID, error)
	// Single package with its active subscription count.
	GetPackageByID(ctx context.Context, id pgtype.UUID) (GetPackageByIDRow, error)
	// ============================================================================
	// 1. Defaults & Seed Checks
	// ============================================================================
	GetPackageBySlug(ctx context.Context, slug string) (Package, error)
	GetPackagePermissionLimit(ctx context.Context, arg GetPackagePermissionLimitParams) (GetPackagePermissionLimitRow, error)
	GetPackagePermissionLimitByEndpoint(ctx context.Context, arg GetPackagePermissionLimitByEndpointParams) (GetPackagePermissionLimitByEndpointRow, error)
	GetPublicBoardBySlug(ctx context.Context, slug string) (GetPublicBoardBySlugRow, error)
	GetRoleById(ctx context.Context, id pgtype.UUID) (GetRoleByIdRow, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetSmartWidgetById(ctx context.Context, arg GetSmartWidgetByIdParams) (GetSmartWidgetByIdRow, error)
	// ============================================================================
	// 2. User & Signup Queries
	// ============================================================================
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	GetUserByResetToken(ctx context.Context, resetPasswordToken pgtype.Text) (User, error)
	// ============================================================================
	// 7. Role Queries
	// ============================================================================
	GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error)
	GetUserPrimaryOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetUserProfileById(ctx context.Context, id pgtype.UUID) (GetUserProfileByIdRow, error)
	GetUserQuotas(ctx context.Context, userID pgtype.UUID) ([]GetUserQuotasRow, error)
	GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error
	GrantUserRoles(ctx context.Context, arg GrantUserRolesParams) error
	IncrementLimitUsage(ctx context.Context, arg IncrementLimitUsageParams) (pgtype.UUID, error)
	InitializeLimitUsage(ctx context.Context, arg InitializeLimitUsageParams) (pgtype.UUID, error)
	InsertPackage(ctx context.Context, arg InsertPackageParams) (pgtype.UUID, error)
	InsertPackagePermissionLimit(ctx context.Context, arg InsertPackagePermissionLimitParams) error
	InsertPermission(ctx context.Context, arg InsertPermissionParams) (InsertPermissionRow, error)
	InsertRole(ctx context.Context, arg InsertRoleParams) (pgtype.UUID, error)
	InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error)
	ListAllPermissions(ctx context.Context) ([]ListAllPermissionsRow, error)
	// ============================================================================
	// 1. Board Queries
	// ============================================================================
	ListBoardsByPrimaryUserId(ctx context.Context, primaryUserID pgtype.UUID) ([]ListBoardsByPrimaryUserIdRow, error)
	ListOrderItemsByOrderId(ctx context.Context, orderID pgtype.UUID) ([]ListOrderItemsByOrderIdRow, error)
	ListOrdersByPrimaryUserID(ctx context.Context, primaryUserID pgtype.UUID) ([]ListOrdersByPrimaryUserIDRow, error)
	// Permission limits (with joined permission metadata) for the given packages.
	ListPackagePermissionLimits(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListPackagePermissionLimitsRow, error)
	// All packages with their active subscription count.
	ListPackages(ctx context.Context) ([]ListPackagesRow, error)
	ListRolePermissionEndpoints(ctx context.Context, roleID pgtype.UUID) ([]ListRolePermissionEndpointsRow, error)
	ListRolePermissionsByRoleIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListRolePermissionsByRoleIDsRow, error)
	ListRolesByPrimaryUserID(ctx context.Context, primaryUserID pgtype.UUID) ([]ListRolesByPrimaryUserIDRow, error)
	// ============================================================================
	// 6. Inventory (Smart Widget) Queries
	// ============================================================================
	ListSmartWidgetsByPrimaryUserId(ctx context.Context, arg ListSmartWidgetsByPrimaryUserIdParams) ([]ListSmartWidgetsByPrimaryUserIdRow, error)
	// ============================================================================
	// Package Queries
	// ============================================================================
	// Permissions exposed for building/assigning package quotas. Mirrors the TS
	// service which joins permissions through the tenant role (TENANT_ROLE_SLUG).
	ListTenantRolePermissions(ctx context.Context, slug string) ([]ListTenantRolePermissionsRow, error)
	ListUserRolesByUserIDs(ctx context.Context, userIds []pgtype.UUID) ([]ListUserRolesByUserIDsRow, error)
	ListWidgetsForOrder(ctx context.Context, arg ListWidgetsForOrderParams) ([]ListWidgetsForOrderRow, error)
	// ============================================================================
	// 8. User Queries
	// ============================================================================
	ListWorkspaceUsers(ctx context.Context, arg ListWorkspaceUsersParams) ([]ListWorkspaceUsersRow, error)
	// ============================================================================
	// 3. Password & Session Management Updates
	// ============================================================================
	SetResetPasswordToken(ctx context.Context, arg SetResetPasswordTokenParams) error
	TruncateAllTables(ctx context.Context) error
	UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error)
	// Partial update of a package. NULL arguments leave the column unchanged.
	UpdatePackage(ctx context.Context, arg UpdatePackageParams) (Package, error)
	UpdatePasswordAndClearTokens(ctx context.Context, arg UpdatePasswordAndClearTokensParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSmartWidget(ctx context.Context, arg UpdateSmartWidgetParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
}

var _ Querier = (*Queries)(nil)
