// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error
	ClearRefreshToken(ctx context.Context, id pgtype.UUID) error
	CountUserSubscriptions(ctx context.Context, userID pgtype.UUID) (int32, error)
	CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error)
	CreateSmartWidget(ctx context.Context, arg CreateSmartWidgetParams) (SmartWidget, error)
	CreateSmartWidgets(ctx context.Context, arg []CreateSmartWidgetsParams) (int64, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementLimitUsage(ctx context.Context, arg DecrementLimitUsageParams) (pgtype.UUID, error)
	DeleteBoard(ctx context.Context, id pgtype.UUID) error
	DeleteSmartWidget(ctx context.Context, id pgtype.UUID) error
	// ============================================================================
	// 4. Access Control (RBAC) & Quotas
	// ============================================================================
	GetAccessContextByUserId(ctx context.Context, userID pgtype.UUID) ([]GetAccessContextByUserIdRow, error)
	GetActiveSubscriptions(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	GetBoardById(ctx context.Context, arg GetBoardByIdParams) (GetBoardByIdRow, error)
	GetBoardBySlug(ctx context.Context, arg GetBoardBySlugParams) (GetBoardBySlugRow, error)
	GetBoardExistsForUser(ctx context.Context, arg GetBoardExistsForUserParams) (bool, error)
	GetBoardIdBySlug(ctx context.Context, slug string) (pgtype.UUID, error)
	GetLimitUsage(ctx context.Context, arg GetLimitUsageParams) (int32, error)
	// ============================================================================
	// 1. Defaults & Seed Checks
	// ============================================================================
	GetPackageBySlug(ctx context.Context, slug string) (Package, error)
	GetPackagePermissionLimit(ctx context.Context, arg GetPackagePermissionLimitParams) (GetPackagePermissionLimitRow, error)
	GetPackagePermissionLimitByEndpoint(ctx context.Context, arg GetPackagePermissionLimitByEndpointParams) (GetPackagePermissionLimitByEndpointRow, error)
	GetPublicBoardBySlug(ctx context.Context, slug string) (GetPublicBoardBySlugRow, error)
	GetRoleBySlug(ctx context.Context, slug string) (Role, error)
	GetSmartWidgetById(ctx context.Context, arg GetSmartWidgetByIdParams) (GetSmartWidgetByIdRow, error)
	// ============================================================================
	// 2. User & Signup Queries
	// ============================================================================
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	GetUserByResetToken(ctx context.Context, resetPasswordToken pgtype.Text) (User, error)
	GetUserPrimaryOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	GetUserQuotas(ctx context.Context, userID pgtype.UUID) ([]GetUserQuotasRow, error)
	GrantRolePermission(ctx context.Context, arg GrantRolePermissionParams) error
	IncrementLimitUsage(ctx context.Context, arg IncrementLimitUsageParams) (pgtype.UUID, error)
	InitializeLimitUsage(ctx context.Context, arg InitializeLimitUsageParams) (pgtype.UUID, error)
	InsertPackage(ctx context.Context, arg InsertPackageParams) (pgtype.UUID, error)
	InsertPackagePermissionLimit(ctx context.Context, arg InsertPackagePermissionLimitParams) error
	InsertPermission(ctx context.Context, arg InsertPermissionParams) (InsertPermissionRow, error)
	InsertRole(ctx context.Context, arg InsertRoleParams) (pgtype.UUID, error)
	InsertSubscription(ctx context.Context, arg InsertSubscriptionParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) (pgtype.UUID, error)
	// ============================================================================
	// 1. Board Queries
	// ============================================================================
	ListBoardsByPrimaryUserId(ctx context.Context, primaryUserID pgtype.UUID) ([]ListBoardsByPrimaryUserIdRow, error)
	// ============================================================================
	// 6. Inventory (Smart Widget) Queries
	// ============================================================================
	ListSmartWidgetsByPrimaryUserId(ctx context.Context, arg ListSmartWidgetsByPrimaryUserIdParams) ([]ListSmartWidgetsByPrimaryUserIdRow, error)
	// ============================================================================
	// 3. Password & Session Management Updates
	// ============================================================================
	SetResetPasswordToken(ctx context.Context, arg SetResetPasswordTokenParams) error
	TruncateAllTables(ctx context.Context) error
	UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error)
	UpdatePasswordAndClearTokens(ctx context.Context, arg UpdatePasswordAndClearTokensParams) error
	UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error
	UpdateSmartWidget(ctx context.Context, arg UpdateSmartWidgetParams) error
}

var _ Querier = (*Queries)(nil)
