// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realtime.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlacedWidgets = `-- name: GetPlacedWidgets :many
SELECT id, name, sku, photo, price, quantity, pos_x, pos_y, width, height
FROM smart_widgets
WHERE board_id = $1
  AND pos_x IS NOT NULL
ORDER BY created_at DESC
`

type GetPlacedWidgetsRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Sku      string         `json:"sku"`
	Photo    pgtype.Text    `json:"photo"`
	Price    pgtype.Numeric `json:"price"`
	Quantity int32          `json:"quantity"`
	PosX     pgtype.Numeric `json:"pos_x"`
	PosY     pgtype.Numeric `json:"pos_y"`
	Width    int32          `json:"width"`
	Height   int32          `json:"height"`
}

// Placed widgets for a board: those that already carry canvas coordinates
// (pos_x IS NOT NULL). Sidebar inventory items have NULL coordinates and are
// excluded until they are first placed.
func (q *Queries) GetPlacedWidgets(ctx context.Context, boardID pgtype.UUID) ([]GetPlacedWidgetsRow, error) {
	rows, err := q.db.Query(ctx, getPlacedWidgets, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPlacedWidgetsRow
	for rows.Next() {
		var i GetPlacedWidgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Photo,
			&i.Price,
			&i.Quantity,
			&i.PosX,
			&i.PosY,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRealtimeBoardBySlug = `-- name: GetRealtimeBoardBySlug :one

SELECT id, slug, name, access, max_width, max_height
FROM boards
WHERE slug = $1
`

type GetRealtimeBoardBySlugRow struct {
	ID        pgtype.UUID `json:"id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	Access    string      `json:"access"`
	MaxWidth  pgtype.Int4 `json:"max_width"`
	MaxHeight pgtype.Int4 `json:"max_height"`
}

// ============================================================================
// Realtime Canvas Queries
// ============================================================================
// Lookup a board by its public slug. Returned regardless of access level; the
// gateway decides whether anonymous (public) or authenticated (private) access
// is allowed based on the `access` column.
func (q *Queries) GetRealtimeBoardBySlug(ctx context.Context, slug string) (GetRealtimeBoardBySlugRow, error) {
	row := q.db.QueryRow(ctx, getRealtimeBoardBySlug, slug)
	var i GetRealtimeBoardBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Access,
		&i.MaxWidth,
		&i.MaxHeight,
	)
	return i, err
}

const getUserWidgetPermissions = `-- name: GetUserWidgetPermissions :many
SELECT p.action, p.subject
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
`

type GetUserWidgetPermissionsRow struct {
	Action  string `json:"action"`
	Subject string `json:"subject"`
}

// The set of (action, subject) grants a user holds through their roles. Used to
// decide whether an authenticated editor may reposition widgets on the canvas
// (requires update:SmartWidget).
func (q *Queries) GetUserWidgetPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserWidgetPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserWidgetPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWidgetPermissionsRow
	for rows.Next() {
		var i GetUserWidgetPermissionsRow
		if err := rows.Scan(&i.Action, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeWidget = `-- name: RemoveWidget :exec
DELETE FROM smart_widgets
WHERE id = $1
  AND board_id = $2
`

type RemoveWidgetParams struct {
	ID      pgtype.UUID `json:"id"`
	BoardID pgtype.UUID `json:"board_id"`
}

// Permanently remove a sold/purchased widget, board-scoped.
func (q *Queries) RemoveWidget(ctx context.Context, arg RemoveWidgetParams) error {
	_, err := q.db.Exec(ctx, removeWidget, arg.ID, arg.BoardID)
	return err
}

const updateWidgetPosition = `-- name: UpdateWidgetPosition :one
UPDATE smart_widgets
SET pos_x = $1,
    pos_y = $2,
    updated_at = NOW()
WHERE id = $3
  AND board_id = $4
RETURNING id, name, sku, photo, price, quantity, pos_x, pos_y, width, height
`

type UpdateWidgetPositionParams struct {
	PosX    pgtype.Numeric `json:"pos_x"`
	PosY    pgtype.Numeric `json:"pos_y"`
	ID      pgtype.UUID    `json:"id"`
	BoardID pgtype.UUID    `json:"board_id"`
}

type UpdateWidgetPositionRow struct {
	ID       pgtype.UUID    `json:"id"`
	Name     string         `json:"name"`
	Sku      string         `json:"sku"`
	Photo    pgtype.Text    `json:"photo"`
	Price    pgtype.Numeric `json:"price"`
	Quantity int32          `json:"quantity"`
	PosX     pgtype.Numeric `json:"pos_x"`
	PosY     pgtype.Numeric `json:"pos_y"`
	Width    int32          `json:"width"`
	Height   int32          `json:"height"`
}

// Stamp new canvas coordinates onto a widget, board-scoped so a stray id can't
// touch another board's row. Returns the full row so callers can read the
// widget's stored dimensions (width/height) for zone calculations.
func (q *Queries) UpdateWidgetPosition(ctx context.Context, arg UpdateWidgetPositionParams) (UpdateWidgetPositionRow, error) {
	row := q.db.QueryRow(ctx, updateWidgetPosition,
		arg.PosX,
		arg.PosY,
		arg.ID,
		arg.BoardID,
	)
	var i UpdateWidgetPositionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Photo,
		&i.Price,
		&i.Quantity,
		&i.PosX,
		&i.PosY,
		&i.Width,
		&i.Height,
	)
	return i, err
}
