// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    slug,
    title,
    primary_user_id,
    secondary_user_id
)
VALUES ($1, $2, $3, $4)
RETURNING id, title, slug, primary_user_id, secondary_user_id
`

type CreateRoleParams struct {
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Slug,
		arg.Title,
		arg.PrimaryUserID,
		arg.SecondaryUserID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}

const createRolePermissions = `-- name: CreateRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1::uuid, x
FROM unnest($2::uuid[]) AS x
`

type CreateRolePermissionsParams struct {
	RoleID        pgtype.UUID   `json:"role_id"`
	PermissionIds []pgtype.UUID `json:"permission_ids"`
}

func (q *Queries) CreateRolePermissions(ctx context.Context, arg CreateRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, createRolePermissions, arg.RoleID, arg.PermissionIds)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRoleById = `-- name: GetRoleById :one
SELECT r.id, r.title, r.slug, r.primary_user_id, r.secondary_user_id, COUNT(ur.id)::bigint AS member_count
FROM roles r
LEFT JOIN user_roles ur ON ur.role_id = r.id
WHERE r.id = $1
GROUP BY r.id
`

type GetRoleByIdRow struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
	MemberCount     int64       `json:"member_count"`
}

func (q *Queries) GetRoleById(ctx context.Context, id pgtype.UUID) (GetRoleByIdRow, error) {
	row := q.db.QueryRow(ctx, getRoleById, id)
	var i GetRoleByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
		&i.MemberCount,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many

SELECT DISTINCT p.id, p.name, p.action, p.subject, p.description
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
`

type GetUserPermissionsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Action      string      `json:"action"`
	Subject     string      `json:"subject"`
	Description pgtype.Text `json:"description"`
}

// ============================================================================
// 7. Role Queries
// ============================================================================
func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPermissionsRow
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.Subject,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPermissions = `-- name: ListAllPermissions :many
SELECT id, name, action, subject, description
FROM permissions
ORDER BY subject, action
`

type ListAllPermissionsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Action      string      `json:"action"`
	Subject     string      `json:"subject"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) ListAllPermissions(ctx context.Context) ([]ListAllPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllPermissionsRow
	for rows.Next() {
		var i ListAllPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Action,
			&i.Subject,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionEndpoints = `-- name: ListRolePermissionEndpoints :many
SELECT DISTINCT p.endpoint, p.method
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

type ListRolePermissionEndpointsRow struct {
	Endpoint string `json:"endpoint"`
	Method   string `json:"method"`
}

func (q *Queries) ListRolePermissionEndpoints(ctx context.Context, roleID pgtype.UUID) ([]ListRolePermissionEndpointsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissionEndpoints, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionEndpointsRow
	for rows.Next() {
		var i ListRolePermissionEndpointsRow
		if err := rows.Scan(&i.Endpoint, &i.Method); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionsByRoleIDs = `-- name: ListRolePermissionsByRoleIDs :many
SELECT rp.role_id,
       p.id AS permission_id,
       p.name AS permission_name,
       p.action AS permission_action,
       p.subject AS permission_subject
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = ANY($1::uuid[])
`

type ListRolePermissionsByRoleIDsRow struct {
	RoleID            pgtype.UUID `json:"role_id"`
	PermissionID      pgtype.UUID `json:"permission_id"`
	PermissionName    string      `json:"permission_name"`
	PermissionAction  string      `json:"permission_action"`
	PermissionSubject string      `json:"permission_subject"`
}

func (q *Queries) ListRolePermissionsByRoleIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListRolePermissionsByRoleIDsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissionsByRoleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionsByRoleIDsRow
	for rows.Next() {
		var i ListRolePermissionsByRoleIDsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionAction,
			&i.PermissionSubject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByPrimaryUserID = `-- name: ListRolesByPrimaryUserID :many
SELECT r.id, r.title, r.slug, r.primary_user_id, r.secondary_user_id, COUNT(ur.id)::bigint AS member_count
FROM roles r
LEFT JOIN user_roles ur ON ur.role_id = r.id
WHERE r.primary_user_id = $1
GROUP BY r.id
ORDER BY r.title
`

type ListRolesByPrimaryUserIDRow struct {
	ID              pgtype.UUID `json:"id"`
	Title           string      `json:"title"`
	Slug            string      `json:"slug"`
	PrimaryUserID   pgtype.UUID `json:"primary_user_id"`
	SecondaryUserID pgtype.UUID `json:"secondary_user_id"`
	MemberCount     int64       `json:"member_count"`
}

func (q *Queries) ListRolesByPrimaryUserID(ctx context.Context, primaryUserID pgtype.UUID) ([]ListRolesByPrimaryUserIDRow, error) {
	rows, err := q.db.Query(ctx, listRolesByPrimaryUserID, primaryUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesByPrimaryUserIDRow
	for rows.Next() {
		var i ListRolesByPrimaryUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.PrimaryUserID,
			&i.SecondaryUserID,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET title = $1
WHERE id = $2
RETURNING id, title, slug, primary_user_id, secondary_user_id
`

type UpdateRoleParams struct {
	Title string      `json:"title"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Title, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.PrimaryUserID,
		&i.SecondaryUserID,
	)
	return i, err
}
