// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserSubscriptions = `-- name: CountUserSubscriptions :one
SELECT COUNT(*)::int
FROM subscriptions
WHERE user_id = $1
`

func (q *Queries) CountUserSubscriptions(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUserSubscriptions, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSubscriptionReturning = `-- name: CreateSubscriptionReturning :one
INSERT INTO subscriptions (
    user_id,
    package_id,
    start_date,
    end_date,
    payment_method,
    amount
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, package_id, start_date, end_date, payment_method, amount
`

type CreateSubscriptionReturningParams struct {
	UserID        pgtype.UUID      `json:"user_id"`
	PackageID     pgtype.UUID      `json:"package_id"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	PaymentMethod string           `json:"payment_method"`
	Amount        pgtype.Numeric   `json:"amount"`
}

// Create a subscription and return the inserted row.
func (q *Queries) CreateSubscriptionReturning(ctx context.Context, arg CreateSubscriptionReturningParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscriptionReturning,
		arg.UserID,
		arg.PackageID,
		arg.StartDate,
		arg.EndDate,
		arg.PaymentMethod,
		arg.Amount,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PackageID,
		&i.StartDate,
		&i.EndDate,
		&i.PaymentMethod,
		&i.Amount,
	)
	return i, err
}

const decrementLimitUsage = `-- name: DecrementLimitUsage :one
UPDATE limit_usages
SET used = GREATEST(used - 1, 0)
WHERE user_id = $1
  AND package_permission_limit_id = $2
RETURNING id
`

type DecrementLimitUsageParams struct {
	UserID                   pgtype.UUID `json:"user_id"`
	PackagePermissionLimitID pgtype.UUID `json:"package_permission_limit_id"`
}

func (q *Queries) DecrementLimitUsage(ctx context.Context, arg DecrementLimitUsageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, decrementLimitUsage, arg.UserID, arg.PackagePermissionLimitID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveSubscriptions = `-- name: GetActiveSubscriptions :many
SELECT package_id
FROM subscriptions
WHERE user_id = $1
  AND (end_date IS NULL OR end_date > NOW())
ORDER BY start_date
`

func (q *Queries) GetActiveSubscriptions(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getActiveSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var package_id pgtype.UUID
		if err := rows.Scan(&package_id); err != nil {
			return nil, err
		}
		items = append(items, package_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLimitUsage = `-- name: GetLimitUsage :one
SELECT used
FROM limit_usages
WHERE user_id = $1
  AND package_permission_limit_id = $2
LIMIT 1
`

type GetLimitUsageParams struct {
	UserID                   pgtype.UUID `json:"user_id"`
	PackagePermissionLimitID pgtype.UUID `json:"package_permission_limit_id"`
}

func (q *Queries) GetLimitUsage(ctx context.Context, arg GetLimitUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, getLimitUsage, arg.UserID, arg.PackagePermissionLimitID)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const getPackagePermissionLimit = `-- name: GetPackagePermissionLimit :one
SELECT 
    ppl.id,
    ppl.limit_count
FROM package_permission_limits ppl
JOIN permissions p ON ppl.permission_id = p.id
WHERE ppl.package_id = $1
  AND p.action = $2
  AND p.subject = $3
LIMIT 1
`

type GetPackagePermissionLimitParams struct {
	PackageID pgtype.UUID `json:"package_id"`
	Action    string      `json:"action"`
	Subject   string      `json:"subject"`
}

type GetPackagePermissionLimitRow struct {
	ID         pgtype.UUID `json:"id"`
	LimitCount pgtype.Int4 `json:"limit_count"`
}

func (q *Queries) GetPackagePermissionLimit(ctx context.Context, arg GetPackagePermissionLimitParams) (GetPackagePermissionLimitRow, error) {
	row := q.db.QueryRow(ctx, getPackagePermissionLimit, arg.PackageID, arg.Action, arg.Subject)
	var i GetPackagePermissionLimitRow
	err := row.Scan(&i.ID, &i.LimitCount)
	return i, err
}

const getPackagePermissionLimitByEndpoint = `-- name: GetPackagePermissionLimitByEndpoint :one
SELECT 
    ppl.id,
    ppl.limit_count
FROM package_permission_limits ppl
JOIN permissions p ON ppl.permission_id = p.id
WHERE ppl.package_id = $1
  AND p.endpoint = $2
  AND p.method = $3
LIMIT 1
`

type GetPackagePermissionLimitByEndpointParams struct {
	PackageID pgtype.UUID `json:"package_id"`
	Endpoint  string      `json:"endpoint"`
	Method    string      `json:"method"`
}

type GetPackagePermissionLimitByEndpointRow struct {
	ID         pgtype.UUID `json:"id"`
	LimitCount pgtype.Int4 `json:"limit_count"`
}

func (q *Queries) GetPackagePermissionLimitByEndpoint(ctx context.Context, arg GetPackagePermissionLimitByEndpointParams) (GetPackagePermissionLimitByEndpointRow, error) {
	row := q.db.QueryRow(ctx, getPackagePermissionLimitByEndpoint, arg.PackageID, arg.Endpoint, arg.Method)
	var i GetPackagePermissionLimitByEndpointRow
	err := row.Scan(&i.ID, &i.LimitCount)
	return i, err
}

const getSubscriptionByUserAndPackage = `-- name: GetSubscriptionByUserAndPackage :one
SELECT id
FROM subscriptions
WHERE user_id = $1
  AND package_id = $2
LIMIT 1
`

type GetSubscriptionByUserAndPackageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	PackageID pgtype.UUID `json:"package_id"`
}

// Look up a single subscription for a user + package pair. Used to block
// duplicate Free-package subscriptions.
func (q *Queries) GetSubscriptionByUserAndPackage(ctx context.Context, arg GetSubscriptionByUserAndPackageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserAndPackage, arg.UserID, arg.PackageID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserPrimaryOwner = `-- name: GetUserPrimaryOwner :one

SELECT primary_user_id
FROM users
WHERE id = $1
`

// ============================================================================
// Limit Guard Queries (do not remove — consumed by auth middleware)
// ============================================================================
func (q *Queries) GetUserPrimaryOwner(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserPrimaryOwner, id)
	var primary_user_id pgtype.UUID
	err := row.Scan(&primary_user_id)
	return primary_user_id, err
}

const incrementLimitUsage = `-- name: IncrementLimitUsage :one
UPDATE limit_usages
SET used = used + 1
WHERE user_id = $1
  AND package_permission_limit_id = $2
  AND used < $3
RETURNING id
`

type IncrementLimitUsageParams struct {
	UserID                   pgtype.UUID `json:"user_id"`
	PackagePermissionLimitID pgtype.UUID `json:"package_permission_limit_id"`
	Used                     int32       `json:"used"`
}

func (q *Queries) IncrementLimitUsage(ctx context.Context, arg IncrementLimitUsageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, incrementLimitUsage, arg.UserID, arg.PackagePermissionLimitID, arg.Used)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const initializeLimitUsage = `-- name: InitializeLimitUsage :one
INSERT INTO limit_usages (
    user_id,
    package_permission_limit_id,
    used
) VALUES (
    $1, $2, 1
)
RETURNING id
`

type InitializeLimitUsageParams struct {
	UserID                   pgtype.UUID `json:"user_id"`
	PackagePermissionLimitID pgtype.UUID `json:"package_permission_limit_id"`
}

func (q *Queries) InitializeLimitUsage(ctx context.Context, arg InitializeLimitUsageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, initializeLimitUsage, arg.UserID, arg.PackagePermissionLimitID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listSubscriptionsByUser = `-- name: ListSubscriptionsByUser :many

SELECT
    s.id,
    s.package_id,
    p.title AS package_title,
    p.slug  AS package_slug,
    s.start_date,
    s.end_date,
    s.payment_method,
    s.amount
FROM subscriptions s
JOIN packages p ON p.id = s.package_id
WHERE s.user_id = $1
ORDER BY s.start_date DESC
`

type ListSubscriptionsByUserRow struct {
	ID            pgtype.UUID      `json:"id"`
	PackageID     pgtype.UUID      `json:"package_id"`
	PackageTitle  string           `json:"package_title"`
	PackageSlug   string           `json:"package_slug"`
	StartDate     pgtype.Timestamp `json:"start_date"`
	EndDate       pgtype.Timestamp `json:"end_date"`
	PaymentMethod string           `json:"payment_method"`
	Amount        pgtype.Numeric   `json:"amount"`
}

// ============================================================================
// Subscription Service Queries
// ============================================================================
// List a user's subscriptions joined with their package details, newest first.
func (q *Queries) ListSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]ListSubscriptionsByUserRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsByUserRow
	for rows.Next() {
		var i ListSubscriptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.PackageID,
			&i.PackageTitle,
			&i.PackageSlug,
			&i.StartDate,
			&i.EndDate,
			&i.PaymentMethod,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
