// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubUser = `-- name: CreateSubUser :one
INSERT INTO users (name, email, password, provider, primary_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, provider
`

type CreateSubUserParams struct {
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Password      pgtype.Text `json:"password"`
	Provider      pgtype.Text `json:"provider"`
	PrimaryUserID pgtype.UUID `json:"primary_user_id"`
}

type CreateSubUserRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Provider pgtype.Text `json:"provider"`
}

func (q *Queries) CreateSubUser(ctx context.Context, arg CreateSubUserParams) (CreateSubUserRow, error) {
	row := q.db.QueryRow(ctx, createSubUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Provider,
		arg.PrimaryUserID,
	)
	var i CreateSubUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
	)
	return i, err
}

const deleteSubUser = `-- name: DeleteSubUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteSubUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubUser, id)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles
WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getUserProfileById = `-- name: GetUserProfileById :one
SELECT id, name, email, provider
FROM users
WHERE id = $1
`

type GetUserProfileByIdRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Provider pgtype.Text `json:"provider"`
}

func (q *Queries) GetUserProfileById(ctx context.Context, id pgtype.UUID) (GetUserProfileByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileById, id)
	var i GetUserProfileByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
	)
	return i, err
}

const grantUserRoles = `-- name: GrantUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1::uuid, x
FROM unnest($2::uuid[]) AS x
`

type GrantUserRolesParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	RoleIds []pgtype.UUID `json:"role_ids"`
}

func (q *Queries) GrantUserRoles(ctx context.Context, arg GrantUserRolesParams) error {
	_, err := q.db.Exec(ctx, grantUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const listUserRolesByUserIDs = `-- name: ListUserRolesByUserIDs :many
SELECT DISTINCT ur.user_id, r.id AS role_id, r.title, r.slug
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = ANY($1::uuid[])
`

type ListUserRolesByUserIDsRow struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
	Title  string      `json:"title"`
	Slug   string      `json:"slug"`
}

func (q *Queries) ListUserRolesByUserIDs(ctx context.Context, userIds []pgtype.UUID) ([]ListUserRolesByUserIDsRow, error) {
	rows, err := q.db.Query(ctx, listUserRolesByUserIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRolesByUserIDsRow
	for rows.Next() {
		var i ListUserRolesByUserIDsRow
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.Title,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceUsers = `-- name: ListWorkspaceUsers :many

SELECT id, name, email, provider
FROM users
WHERE id <> $1::uuid
  AND (
    primary_user_id = $2::uuid
    OR id = $2::uuid
  )
ORDER BY name
`

type ListWorkspaceUsersParams struct {
	ExcludeUserID pgtype.UUID `json:"exclude_user_id"`
	ScopeUserID   pgtype.UUID `json:"scope_user_id"`
}

type ListWorkspaceUsersRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Provider pgtype.Text `json:"provider"`
}

// ============================================================================
// 8. User Queries
// ============================================================================
func (q *Queries) ListWorkspaceUsers(ctx context.Context, arg ListWorkspaceUsersParams) ([]ListWorkspaceUsersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceUsers, arg.ExcludeUserID, arg.ScopeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceUsersRow
	for rows.Next() {
		var i ListWorkspaceUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name = COALESCE($1, name),
    email = COALESCE($2, email),
    password = COALESCE($3, password)
WHERE id = $4
RETURNING id, name, email, provider
`

type UpdateUserProfileParams struct {
	Name     pgtype.Text `json:"name"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
	ID       pgtype.UUID `json:"id"`
}

type UpdateUserProfileRow struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Provider pgtype.Text `json:"provider"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Provider,
	)
	return i, err
}
