replicaCount: 1

image:
  repository: loot-board/web
  tag: tilt
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

secrets:
  NODE_ENV: "development"
  PORT: "3000"
  ACCESS_TOKEN_SECRET: "92384ruqwlkerwaq9w8erwqjlasdfs-096-34-324ruisdjflk12"
  REFRESH_TOKEN_SECRET: "spdfjg304rdafkjasdf=-092348902jlskdfsdof03947587342-945fdk"
  GATEWAY_URL: "http://lootboard-api:3001"
  NEXT_PUBLIC_GATEWAY_URL: "http://localhost:3001"
  NEXT_PUBLIC_SOCKET_URL: "http://localhost:3001"
