replicaCount: 1

image:
  repository: asiful087/loot-board-web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

secrets:
  NODE_ENV: "production"
  PORT: "3000"
  ACCESS_TOKEN_SECRET: ""
  REFRESH_TOKEN_SECRET: ""
  GATEWAY_URL: ""
