name: todo-golang

services:
  # ==================================== Infrastructure ==============================

  todo-golang-db:
    container_name: todo-golang-db-container
    image: mongo:latest
    restart: always
    command: mongod --bind_ip_all
  # ==================================== Application Services ==============================

  todo-golang-backend:
    container_name: todo-golang-backend-container
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always

    environment:
      - MONGODB_URI=${TODO_GOLANG_DB_URI}
      - DATABASE_NAME=${TODO_GOLANG_DB}
    ports:
      - 4000:4000
    volumes:
      - ./:/home/app

    depends_on:
      - todo-golang-db

    # 🌟 ADDED UID/GID MAPPING 🌟
    # user: "${UID}:${GID}"
